# Cloud Build config to run a SQL migration on Cloud SQL (Postgres)
# without requiring psql on the developer machine.
#
# Usage example:
# gcloud builds submit . --config cloudbuild.migrate.yaml \
#   --substitutions=_INSTANCE_CONNECTION_NAME="PROJECT:REGION:INSTANCE",_DATABASE_URL_SECRET_NAME="idiomasbr-database-url",_MIGRATION_FILE="backend/migrations/add_is_admin_to_users.sql"

substitutions:
  _INSTANCE_CONNECTION_NAME: ""
  _DATABASE_URL_SECRET_NAME: ""
  _MIGRATION_FILE: ""

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -ceu
      - |
        if [[ -z "${_INSTANCE_CONNECTION_NAME}" ]]; then
          echo "Erro: _INSTANCE_CONNECTION_NAME não definido"; exit 1
        fi
        if [[ -z "${_DATABASE_URL_SECRET_NAME}" ]]; then
          echo "Erro: _DATABASE_URL_SECRET_NAME não definido"; exit 1
        fi
        if [[ -z "${_MIGRATION_FILE}" ]]; then
          echo "Erro: _MIGRATION_FILE não definido"; exit 1
        fi
        if [[ ! -f "${_MIGRATION_FILE}" ]]; then
          echo "Erro: arquivo de migração não encontrado: ${_MIGRATION_FILE}"; exit 1
        fi

        echo "🔧 Instalando dependências (psql + curl)..."
        apt-get update -y
        apt-get install -y --no-install-recommends postgresql-client curl ca-certificates python3

        echo "🔌 Baixando cloud-sql-proxy..."
        PROXY_URL="https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.4/cloud-sql-proxy.linux.amd64"
        curl -fsSL "$$PROXY_URL" -o /usr/local/bin/cloud-sql-proxy
        chmod +x /usr/local/bin/cloud-sql-proxy

        echo "🔐 Lendo DATABASE_URL do Secret Manager (${_DATABASE_URL_SECRET_NAME})..."
        export DATABASE_URL
        DATABASE_URL="$(gcloud secrets versions access latest --secret="${_DATABASE_URL_SECRET_NAME}")"

        echo "🧩 Extraindo credenciais do DATABASE_URL..."
        PARSED="$(python3 -c "import os; from urllib.parse import urlparse, unquote; u=urlparse(os.environ['DATABASE_URL']); assert u.scheme in ('postgres','postgresql'); user=unquote(u.username or ''); pwd=unquote(u.password or ''); db=(u.path or '/').lstrip('/'); assert user; assert db; print(user); print(pwd); print(db)")"
        export PGUSER PGPASSWORD PGDATABASE
        PGUSER="$(printf '%s' "$$PARSED" | sed -n '1p')"
        PGPASSWORD="$(printf '%s' "$$PARSED" | sed -n '2p')"
        PGDATABASE="$(printf '%s' "$$PARSED" | sed -n '3p')"

        echo "🚀 Iniciando cloud-sql-proxy para ${_INSTANCE_CONNECTION_NAME} (porta 5432)..."
        cloud-sql-proxy "${_INSTANCE_CONNECTION_NAME}" --port 5432 &
        PROXY_PID=$!

        # aguardar proxy subir
        for i in {1..20}; do
          if pg_isready -h 127.0.0.1 -p 5432 -U "$$PGUSER" -d "$$PGDATABASE" >/dev/null 2>&1; then
            break
          fi
          sleep 1
        done

        echo "🗄️ Aplicando migração: ${_MIGRATION_FILE}"
        psql -h 127.0.0.1 -p 5432 -v ON_ERROR_STOP=1 -f "${_MIGRATION_FILE}"

        echo "🧹 Encerrando proxy..."
        kill "$$PROXY_PID" || true

        echo "✅ Migração aplicada com sucesso."

options:
  logging: CLOUD_LOGGING_ONLY
